# Generated by Django 4.2.1 on 2023-05-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('course', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=30)),
                ('phone', models.CharField(default='', max_length=30)),
                ('address', models.CharField(default='', max_length=30)),
                ('profession', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
